import nbformat as nbf
from docx import Document
from fpdf import FPDF
from typing import List, Dict
from pathlib import Path

class ExportManager:
    """Export research papers and summaries to various formats"""
    
    @staticmethod
    def export_to_jupyter(papers: List[Dict], filename: str = "research_papers.ipynb") -> str:
        """Export papers to Jupyter Notebook"""
        nb = nbf.v4.new_notebook()
        
        # Title cell
        nb.cells.append(nbf.v4.new_markdown_cell("# Research Papers Collection\n\nGenerated by Research Buddy"))
        
        # Add each paper
        for i, paper in enumerate(papers, 1):
            # Paper title
            nb.cells.append(nbf.v4.new_markdown_cell(f"## {i}. {paper.get('title', 'Untitled')}"))
            
            # Metadata
            metadata_md = f"""
**Authors**: {paper.get('authors', 'Unknown')}  
**Year**: {paper.get('year', 'N/A')}  
**Citations**: {paper.get('citations', 0)}  
**Source**: {paper.get('source', 'N/A')}  
**URL**: {paper.get('url', 'N/A')}
"""
            nb.cells.append(nbf.v4.new_markdown_cell(metadata_md))
            
            # Abstract
            if paper.get('abstract'):
                nb.cells.append(nbf.v4.new_markdown_cell(f"**Abstract**:\n\n{paper['abstract']}"))
            
            # Code cell for analysis (placeholder)
            code = f"""# Analysis for: {paper.get('title', 'Paper')}
# Add your notes and code here
"""
            nb.cells.append(nbf.v4.new_code_cell(code))
        
        # Save notebook
        output_path = Path("cache/exports") / filename
        output_path.parent.mkdir(parents=True, exist_ok=True)
        
        with open(output_path, 'w', encoding='utf-8') as f:
            nbf.write(nb, f)
        
        return str(output_path)
    
    @staticmethod
    def export_to_latex(papers: List[Dict], filename: str = "research_papers.tex") -> str:
        """Export papers to LaTeX (Overleaf compatible)"""
        latex_content = r"""\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage{hyperref}
\usepackage{biblatex}

\title{Research Papers Collection}
\author{Generated by Research Buddy}
\date{\today}

\begin{document}

\maketitle

\section{Papers}

"""
        
        for i, paper in enumerate(papers, 1):
            title = paper.get('title', 'Untitled').replace('_', '\\_').replace('&', '\\&')
            authors = paper.get('authors', 'Unknown').replace('_', '\\_').replace('&', '\\&')
            abstract = paper.get('abstract', '').replace('_', '\\_').replace('&', '\\&')
            
            latex_content += f"""
\\subsection{{{title}}}

\\textbf{{Authors}}: {authors} \\\\
\\textbf{{Year}}: {paper.get('year', 'N/A')} \\\\
\\textbf{{Citations}}: {paper.get('citations', 0)} \\\\
\\textbf{{URL}}: \\url{{{paper.get('url', '')}}}

\\textbf{{Abstract}}:

{abstract[:500]}...

"""
        
        latex_content += r"""
\end{document}
"""
        
        output_path = Path("cache/exports") / filename
        output_path.parent.mkdir(parents=True, exist_ok=True)
        
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(latex_content)
        
        return str(output_path)
    
    @staticmethod
    def export_to_word(papers: List[Dict], filename: str = "research_papers.docx") -> str:
        """Export papers to Word document"""
        doc = Document()
        
        # Title
        doc.add_heading('Research Papers Collection', 0)
        doc.add_paragraph('Generated by Research Buddy')
        
        # Add each paper
        for i, paper in enumerate(papers, 1):
            doc.add_heading(f"{i}. {paper.get('title', 'Untitled')}", level=1)
            
            # Metadata
            doc.add_paragraph(f"Authors: {paper.get('authors', 'Unknown')}")
            doc.add_paragraph(f"Year: {paper.get('year', 'N/A')}")
            doc.add_paragraph(f"Citations: {paper.get('citations', 0)}")
            doc.add_paragraph(f"URL: {paper.get('url', 'N/A')}")
            
            # Abstract
            if paper.get('abstract'):
                doc.add_heading('Abstract', level=2)
                doc.add_paragraph(paper['abstract'])
            
            doc.add_page_break()
        
        output_path = Path("cache/exports") / filename
        output_path.parent.mkdir(parents=True, exist_ok=True)
        
        doc.save(output_path)
        
        return str(output_path)
    
    @staticmethod
    def export_to_notion_markdown(papers: List[Dict], filename: str = "research_papers.md") -> str:
        """Export papers to Notion-compatible Markdown"""
        md_content = "# Research Papers Collection\n\n"
        md_content += "*Generated by Research Buddy*\n\n---\n\n"
        
        for i, paper in enumerate(papers, 1):
            md_content += f"## {i}. {paper.get('title', 'Untitled')}\n\n"
            md_content += f"**Authors**: {paper.get('authors', 'Unknown')}  \n"
            md_content += f"**Year**: {paper.get('year', 'N/A')}  \n"
            md_content += f"**Citations**: {paper.get('citations', 0)}  \n"
            md_content += f"**Source**: {paper.get('source', 'N/A')}  \n"
            
            if paper.get('url'):
                md_content += f"**Link**: [{paper['url']}]({paper['url']})  \n\n"
            
            if paper.get('abstract'):
                md_content += f"### Abstract\n\n{paper['abstract']}\n\n"
            
            md_content += "---\n\n"
        
        output_path